title: "Anaya Dam"
email: anaya.dam@bsg.ox.ac.uk
github_username: anayadam

logo: /assets/images/profile.jpeg
cv_url: /assets/files/CV_20262.pdf

baseurl: ""
url: "https://anayadam.github.io"

# SEO Settings
name: "Anaya Dam"
description: "I'm a Postdoctoral Research Fellow at the University of Oxford. My research interests in development economics, particularly, gender, and education."

author:
  name: "Anaya Dam"
  email: "anaya.dam @bsg.ox.ac.uk"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude common unneeded files
exclude:
  - .DS_Store
  - Gemfile
  - Gemfile.lock
